/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ThankyouLazyImport = createFileRoute('/thankyou')()
const ContactsLazyImport = createFileRoute('/contacts')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ThankyouLazyRoute = ThankyouLazyImport.update({
  path: '/thankyou',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/thankyou.lazy').then((d) => d.Route))

const ContactsLazyRoute = ContactsLazyImport.update({
  path: '/contacts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contacts.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsLazyImport
      parentRoute: typeof rootRoute
    }
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ContactsLazyRoute,
  ThankyouLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contacts",
        "/thankyou"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/contacts": {
      "filePath": "contacts.lazy.tsx"
    },
    "/thankyou": {
      "filePath": "thankyou.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
